# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jrtplib-static' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jrtplib-static

end

target 'jrtplib-static-OSX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jrtplib-static-OSX

end

target 'Monal' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Fabric'
pod 'Crashlytics'
pod 'Dropbox-iOS-SDK'
pod 'TPCircularBuffer'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SAMKeychain'
#pod 'NXOAuth2Client', '~> 1.2.8'
pod 'CWStatusBarNotification', '~> 2.3.5'
pod 'MWPhotoBrowser', :podspec =>'https://raw.githubusercontent.com/moinku07/MWPhotoBrowser/master/MWPhotoBrowser.podspec'
pod 'SDWebImage', '~> 4.2.2'

  # Pods for Monal

  target 'Monal Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Monal-OSX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #  use_frameworks!
pod 'Fabric'
pod 'Crashlytics'
pod 'Dropbox-OSX-SDK'
#pod 'MASPreferences'
pod 'SAMKeychain'
#pod 'NXOAuth2Client', '~> 1.2.8'
pod 'TPCircularBuffer'
#pod 'Sparkle'


  # Pods for Monal-OSX

  target 'Monal-OSXTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
