# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jrtplib-static' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jrtplib-static

end

target 'jrtplib-static-OSX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jrtplib-static-OSX

end

target 'shareSheet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Fabric'
pod 'Crashlytics'

end

target 'NotificaionService' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Fabric'
pod 'Crashlytics'
pod 'SignalProtocolObjC'
pod 'SignalProtocolC'
pod 'OpenSSL-Universal'
pod 'SAMKeychain'
pod 'TPCircularBuffer'
pod 'CocoaLumberjack'
end

target 'Monal' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Fabric'
pod 'Crashlytics'
pod 'TPCircularBuffer'
pod 'CocoaLumberjack'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SAMKeychain'
#pod 'NXOAuth2Client', '~> 1.2.8'
pod 'CWStatusBarNotification', '~> 2.3.5'
pod 'IDMPhotoBrowser'
pod 'SDWebImage', '~> 4.3.3'
pod 'SignalProtocolObjC'
pod 'SignalProtocolC'
pod 'OpenSSL-Universal'
pod 'DZNEmptyDataSet'
pod 'EAIntroView'
  # Pods for Monal

  target 'Monal Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end



target 'Monal-OSX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
pod 'Fabric'
pod 'Crashlytics'
#pod 'MASPreferences'
pod 'SAMKeychain'
#pod 'NXOAuth2Client', '~> 1.2.8'
pod 'TPCircularBuffer'
pod 'Sparkle'
pod 'SignalProtocolObjC'
pod 'SignalProtocolC'
pod 'OpenSSL-Universal'

  # Pods for Monal-OSX



end
