//
//  ChangePassword.swift
//  Monal
//
//  Created by lissine on 2/8/2024.
//  Copyright © 2024 monal-im.org. All rights reserved.
//

struct ChangePassword: View {
    @Environment(\.dismiss) private var dismiss

    @State private var oldPass = ""
    @State private var newPass = ""
    @State private var newPass2 = ""

    @State private var showAlert = false
    @State private var alertPrompt = AlertPrompt(dismissLabel: Text("Close"))

    @StateObject private var overlay = LoadingOverlayState()

    let accountID: NSNumber

    private func warningAlert(title: Text, message: Text = Text(""), dismissCallback: monal_void_block_t? = nil) {
        alertPrompt.title = title
        alertPrompt.message = message
        showAlert = true
        alertPrompt.dismissCallback = dismissCallback
    }
    private func errorAlert(title: Text, message: Text = Text("")) {
        alertPrompt.title = title
        alertPrompt.message = message
        showAlert = true
        alertPrompt.dismissCallback = nil
    }
    private func successAlert(title: Text, message: Text) {
        alertPrompt.title = title
        alertPrompt.message = message
        showAlert = true
        alertPrompt.dismissCallback = {
            dismiss()
        }
    }
    
    private func passwordChangeProcessing() {
#if IS_ALPHA
        warningAlert(
            title: Text("Ignoring old password!"),
            message: Text("We are in the alpha, ignoring the old password."),
            dismissCallback: realPasswordChangeProcessing
        )
#else
        guard MLXMPPManager.sharedInstance().isValidPassword(oldPass, forAccount: accountID) else {
            errorAlert(
                title: Text("Wrong Password!"),
                message: Text("The current password is not correct.")
            )
            return
        }
        realPasswordChangeProcessing()
#endif
    }
    
    private func realPasswordChangeProcessing() {
        guard let account = MLXMPPManager.sharedInstance().getEnabledAccount(forID: accountID) else {
            errorAlert(
                title: Text("Account Disabled"),
                message: Text("Please enable your account before changing its password.")
            )
            return
        }
        
        guard newPass == newPass2 else {
            errorAlert(
                title: Text("Passwords don't match!"),
                message: Text("The two entries for the new password don't match, check if you have a typo somewhere.")
            )
            return
        }

        showPromisingLoadingOverlay(overlay, headlineView: Text("Changing Password"), descriptionView: Text("")) {
            account.changePassword(newPass)
        }
        .done { _ in
            successAlert(title: Text("Success"), message: Text("The password has been changed"))
        }
        .catch { error in
            errorAlert(title: Text("Error"), message: Text(error.localizedDescription))
        }

    }

    var body: some View {
        Form {
            Section(header: Text("Enter your new password. Passwords may not be empty. They may also be governed by server or company policies.")) {
                if DataLayer.sharedInstance().isPasswordAutogenerated(forAccount:accountID) {
                    TextField(NSLocalizedString("Current Password", comment: ""), text: $oldPass)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                        .onAppear {
                            oldPass = MLXMPPManager.sharedInstance().getPasswordForAccount(accountID)
                        }
                } else {
                    SecureField(NSLocalizedString("Current Password", comment: ""), text: $oldPass)
                }
                SecureField(NSLocalizedString("New Password", comment: ""), text: $newPass)
                SecureField(NSLocalizedString("New Password (repeated)", comment: ""), text: $newPass2)
            }

            Section {
                Button(action: passwordChangeProcessing) {
                    Text("Change Password")
                        .frame(maxWidth: .infinity, alignment: .center)
                }
                .disabled(oldPass.isEmpty || newPass.isEmpty)
            }

        }
        .alert(
            alertPrompt.title,
            isPresented: $showAlert,
            actions: { Button(NSLocalizedString("Close", comment: ""), action: alertPrompt.dismissCallback ?? {}) },
            message: { alertPrompt.message }
        )
        .navigationTitle(Text("Change Password"))
        .navigationBarTitleDisplayMode(NavigationBarItem.TitleDisplayMode.inline)
        .addLoadingOverlay(overlay)
    }
}
