[package]
name = "monal-xml-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
bytes = { version = "1.0" }
rxml = { version = "0.13", default-features = false, features = ["shared_ns", "compact_str", ] }
