name: Check PR title for proper semver

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - beta
      - stable

  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull request number to check"
        required: true
        type: number

permissions: {}

jobs:
  check-pr-semver-title:
    if: github.event.action != 'edited' || github.event.changes.title || github.event.changes.base
    runs-on: ubuntu-latest
    name: Validate PR Title
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Get PR details
        id: find_pr
        env:
          INPUT_PR_NUMBER: ${{ github.event.inputs.pr_number }}
          EVENT_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [ -z "${INPUT_PR_NUMBER}" ]; then
            prNumber=${EVENT_PR_NUMBER}
          else
            prNumber=${INPUT_PR_NUMBER}
          fi
          echo "prNumber=$prNumber" | tee /dev/stderr >> "$GITHUB_OUTPUT"
      - name: Extract PR metadata
        id: pr_metadata
        uses: actions/github-script@v8
        env:
          PR_NUMBER: ${{ steps.find_pr.outputs.prNumber }}
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
            const prNumber = process.env.PR_NUMBER;
            const { data: pull_request } = await github.rest.pulls.get({
              owner: owner,
              repo: repo,
              pull_number: prNumber
            });
            core.setOutput('prTitle', pull_request.title);
            core.setOutput('prTarget', pull_request.base.ref);
      # - name: Check PR title semver format
      #   env:
      #     VERSION: ${{ steps.pr_metadata.outputs.prTitle }}
      #   run: |
      #     version="${VERSION}"
      #     if ! [[ "$version" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]]; then
      #       echo "Invalid semver: '$version'!"
      #       exit 1
      #     fi
      #     echo "Version is proper semver: $version"
      - name: Checkout target branch
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.pr_metadata.outputs.prTarget }}
          fetch-depth: 4096
          persist-credentials: false
      - name: Extract target branch semver
        id: target_metadata
        env:
          TARGET: ${{ steps.pr_metadata.outputs.prTarget }}
        run: |
          version="$(git log -n 1 --merges --pretty=format:%s | sed -E 's/^[\t\n ]*([^\n\t ]+)[\t\n ]+\(([^\n\t ]+)\)[\t\n ]*$/\1/g')"
          if [ -z "$version" ]; then
            echo "Could not find a merge commit in the last 4096 commits of '$TARGET'!"
            exit 2
          fi
          echo "Semver of branch '$TARGET': $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Check PR title semver is valid and greater than target branch semver
        env:
          VERSION: ${{ steps.pr_metadata.outputs.prTitle }}
          TARGET_VERSION: ${{ steps.target_metadata.outputs.version }}
          TARGET: ${{ steps.pr_metadata.outputs.prTarget }}
        run: |
          pysemver() { pipx run --spec semver==3.1.0 pysemver "$@"; }
          if ! pysemver check -- "$VERSION"; then
            echo "Invalid semver in PR title: '$VERSION'!"
            exit 3
          fi
          if ! pysemver check -- "$TARGET_VERSION"; then
            echo "Invalid semver in target branch '$TARGET': '$TARGET_VERSION'!"
            exit 4
          fi
          if [ "$(pysemver compare -- "$VERSION" "$TARGET_VERSION")" != "1" ]; then
            echo "PR semver $VERSION is not greater than semver $TARGET_VERSION of our '$TARGET' branch!"
            exit 5
          fi
          echo "PR version $VERSION is greater than version $TARGET_VERSION of our '$TARGET' branch..."
