# build a new stable release and push it to apple
name: test-release

# Controls when the action will run.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndPublishStable:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Extract version number and changelog from newest merge commit
        id: releasenotes
        run: |
          buildNumber=$(git tag --sort="v:refname" | grep "Build_iOS" | tail -n1 | sed 's/Build_iOS_//g')
          echo "tag=Build_iOS_$buildNumber" | tee /dev/stderr >> "$GITHUB_OUTPUT"
          echo "name=$(git log -n 1 --merges --pretty=format:%s | sed -E 's/^\s*([^\s]+)\s+\(([^\s]+)\)$/\1 (Build '$buildNumber', PR \2)/g')" | tee /dev/stderr >> "$GITHUB_OUTPUT"
          echo "notes=$(git log -n 1 --merges --pretty=format:%b)" | tee /dev/stderr >> "$GITHUB_OUTPUT"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ steps.releasenotes.outputs.name }}"
          tag_name: "${{ steps.releasenotes.outputs.tag }}"
          target_commitish: stable
          generate_release_notes: false
          body: "${{ steps.releasenotes.outputs.notes }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
