# build a new beta release and push it to apple
name: update-translations

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      arg2:
        description: 'Commit changes?'     
        required: true
        default: 'NOCOMMIT'
      arg3:
        description: 'Compile Swift (YES/NO)'
        required: true
        default: 'YES'

permissions: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  updateTranslations:
    # The type of runner that the job will run on
    runs-on: self-hosted
    permissions:
      contents: write # needed for git push in updateLocalization
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: true
          fetch-depth: 100
          fetch-tags: true
          show-progress: true
          lfs: true
      - name: Checkout submodules
        run: git submodule update -f --init --remote
      - name: Update translations
        run: |
          chmod +x ./scripts/updateLocalization.sh
          chmod +x ./scripts/xliff_extractor.py
          ./scripts/updateLocalization.sh BUILDSERVER "${{ github.event.inputs.arg2 }}" "${{ github.event.inputs.arg3 }}"
